//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nf.protoscript.test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("npsParser.test.parserBasics.70.TextResources", typeof(TextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $ThisIsASingleton
        ///
        ///$applet GApp
        ///
        ///unit tank
        ///
        ///unit tower
        ///
        ///class testMemberDefs
        ///	-integer Number1 @TestAttr
        ///	-integer Number2 = 100 @TestAttr=100
        ///	- Number3 = 10
        ///		@TestAttr=10
        ///	-Number4:integer = 20
        ///	-n NumberA1
        ///	-n NumberA2 = 100
        ///	- NumberA4:n = 20
        ///
        ///class testMethodDefs
        ///	+FuncVV0 = cout(&quot;hello world!&quot;)
        ///	+FuncVI0(InP0:integer) = cout(InP0)
        ///	+FuncIV0:integer = return 99
        ///	+FuncII0(InP0:integer):integer = return InP0
        ///	+ FuncVV1 = cout(&quot;hello world too!&quot;)
        ///	+ FuncVI1(InP0:n) = cout(InP0)
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCodeFile {
            get {
                return ResourceManager.GetString("TestCodeFile", resourceCulture);
            }
        }
    }
}
