//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nf.protoscript.test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("npsParser.test.ClassTranslator.70.resx70.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Name: Get
        ///  Params: []
        ///  Condition: Type_Name == &apos;Constant&apos;
        ///  Code: ${ValueString}
        ///- Name: Get
        ///  Params: []
        ///  Condition: Type_Name == &apos;Constant&apos; &amp; ValueType == &apos;string&apos;
        ///  Code: &apos;&quot;${ValueString}&quot;&apos;
        ///- Name: Get
        ///  Params: []
        ///  Condition: Type_Name == &apos;BinaryOp&apos;
        ///  Code: ${LHS.Get()} ${OpCode} ${RHS.Get()}
        ///- Name: Get
        ///  Params: []
        ///  Condition: Type_Name == &apos;UnaryOp&apos;
        ///  Code: ${OpCode} ${RHS.Get()}
        ///- Name: Get
        ///  Params: []
        ///  Condition: Type_Name == &apos;Assign&apos;
        ///  Code: ${LHS.Set(RHS.Get())}
        ///- Name [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExpressionSchemes {
            get {
                return ResourceManager.GetString("ExpressionSchemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Name: CommonTypeTranslator
        ///  Params: []
        ///  Condition: &quot;&quot;
        ///  Code: |
        ///    class ${Name} {
        ///        constructor() {
        ///            ${for(&apos;member&apos;, $NL, &apos;PropertyInit&apos;)}
        ///        }
        ///        ${for(&apos;method&apos;, $NL, &apos;MethodDecl&apos;)}
        ///    }
        ///
        ///- Name: PropertyInit
        ///  Params: []
        ///  Condition: &quot;&quot;
        ///  Code: this.${Name} = ${InitSyntax.Get()};
        ///
        ///- Name: MethodDecl
        ///  Params: []
        ///  Condition: &quot;&quot;
        ///  Code: |
        ///    function ${Name}(${for(&apos;member&apos;, &apos;, &apos;, &apos;MethodParamDecl&apos;)}) {
        ///        ${InitSyntax.MethodBody()}
        ///    }
        ///
        ///- Na [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Schemes_GearsetJSTranslatorSchemes {
            get {
                return ResourceManager.GetString("Schemes_GearsetJSTranslatorSchemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Name: CommonTypeTranslator
        ///  Params: []
        ///  Condition: &quot;&quot;
        ///  Code: |
        ///    &lt;${Header} Name=&quot;${Name}&quot;&gt;
        ///        &lt;properties&gt;
        ///            ${for(&quot;member&quot;, $NL, &quot;PropertyTranslator&quot;)}
        ///        &lt;/properties&gt;
        ///        &lt;ctor&gt;
        ///            ${for(&quot;member&quot;, $NL, &quot;CtorInitTranslator&quot;)}
        ///        &lt;/ctor&gt;
        ///        &lt;methods&gt;
        ///            ${for(&quot;method&quot;, $NL, &quot;MethodTranslator&quot;)}
        ///        &lt;/methods&gt;
        ///    &lt;/${Header}&gt;
        ///
        ///- Name: PropertyTranslator
        ///  Params: []
        ///  Condition: &quot;&quot;
        ///  Code: |
        ///    &lt;${Header} Name=&quot;${Name}&quot; Ty [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Schemes_XmlTranslatorSchemes {
            get {
                return ResourceManager.GetString("Schemes_XmlTranslatorSchemes", resourceCulture);
            }
        }
    }
}
